### ISSUE TITLE
Debugger window not working

### ISSUE THREAD

**Issue by tannerhallman** [carlosCharz/fcmxmppserver#1]
Firstly, thanks for this project. Helped me greatly. I followed your tutorial but the debug window is not appearing when I initialize the CcsClient with debuggable set to true. I am able to see messages per usual in the console window of IntelliJ. Did you run into this issue? 

`config.setDebuggerEnabled(true); //mDebuggable`

**Comment by carlosCharz** [comment]
Hi.
1. In this smack version you are supposed to see it. I showed in the demo.
2. In my other video (smack upgrade). There is no extra window anymore. They log details in console instead.
Hope you can solve that problem. For number 1 as far as I know. In the server I had some problems but in my localhost not. It was as in my video.
