### ISSUE TITLE
FCM Server Key soon deprecated !

### ISSUE THREAD

**Issue by KoolKeith** [carlosCharz/fcmxmppserver#2]
Hello,
thx for doing this! I managed to successfully test-use it. I have a good feeling that the lib is behaving nicely towards GCM, according to all "etiquette" which google expects (better than that python solution). This solution solves my problems. 

But I have one fear that it will **not** work "forever", as is,  because google console shows a big deprecation warning (can only see the german text right now). It says "Server key" will be deprecated and soon the "**Firebase Cloud Messaging-Token**" must be used instead. Not difficult for you to adapt to this, when the time comes, right? 

And it's awesome that you managed to use a newer smack version. In an earlier project it was impossible for me, and I had to use a very old and very specific smack version in an Android app!

Regards

**Comment by tannerhallman** [comment]
Hey @KoolKeith, don't fret. I noticed this issue and was able to successfully replace the server key with the Firebase Cloud Messaging token in the xampp server and it worked as expected. :)

`final String fcmServerKey = "..."`
![screen shot 2016-11-30 at 7 08 54 pm copy](https://cloud.githubusercontent.com/assets/10327491/20776880/3739cb66-b731-11e6-8bcb-74af12025882.png)

**Comment by KoolKeith** [comment]
Aha, very good news! Thanks for being so "brave" to just swap those keys, haha :) Will try it too :)

**Comment by carlosCharz** [comment]
Yes!! In fact I also have replaced. Now it is about names. They are
changing everytime but hopefully easy stuffs. Wish you the best!

**Comment by carlosCharz** [comment]
They just change that value to server key and the old one is called: Legacy server key. In my project the user provides such that information through the command line so there is no change in the code. Thanks!
