### ISSUE TITLE
java.net.SocketException: Permission denied: connection to (10, [2607:f8b0:4001:c06::bc]:5236,6) denied due to policy

### ISSUE THREAD

**Issue by Edijae** [carlosCharz/fcmxmppserver#3]
I am trying to implement FCM xammp server  in my google cloud module(endpoint) which i latter deploy it to appengine but am getting the error below when try to call `css.connect()`.

```
CcsClient ccs = CcsClient.prepareClient(Utils.FCM_ID,Utils.FCM_KEY,false); 
  try {
      ccs.connect();
      JSONObject jsonObject = new JSONObject();
      jsonObject.put("to",clientId);
      jsonObject.put("message_id",345609);
      jsonObject.put("priority","high");
      JSONObject data = new JSONObject();
      data.put("success",false);
      jsonObject.put("data",data);
      ccs.send(jsonObject.toString());
    } catch (XMPPException | SmackException | IOException e) {
      e.printStackTrace();
    }
```

Error is 

`The following addresses failed: 'fcm-xmpp.googleapis.com:5236' failed because java.net.SocketException: Permission denied: connection to (10, [2607:f8b0:4001:c06::bc]:5236,6) denied due to policy `

**Comment by carlosCharz** [comment]
Hi! I have no idea about this error. It seems that it is a problem with
your endpoints. Have you tried firstdeploying and testing messages
localhost? If so. The problem would be the app engine.  Greetings!
