### ISSUE TITLE
Is not delivered to phone (android)

### ISSUE THREAD

**Issue by fruitJazzy** [carlosCharz/fcmxmppserver#5]
Hello

Try to use your library. Send messag but delivered push to phone. Can you tell what the problem is? 

`06:46:36 PM SENT (0): <stream:stream xmlns='jabber:client' to='FCM XMPP Client Connection Server' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xml:lang='en'>
06:46:36 PM RECV (0): <stream:stream from="FCM XMPP Client Connection Server" id="7CC66277CAAAFA41" version="1.0" xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client">
06:46:36 PM RECV (0): <stream:features><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>X-OAUTH2</mechanism><mechanism>X-GOOGLE-TOKEN</mechanism><mechanism>PLAIN</mechanism></mechanisms></stream:features>
06:46:36 PM SENT (0): <auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='PLAIN'>ADI3MTIwMTY3MzIxNkBnY20uZ29vZ2xlYXBpcy5jb20AQUl6YVN5QmI2NnM4M1RCZExYQ095Um1VRFRMb0RNcG5rQzJSRXJN</auth>
06:46:37 PM RECV (0): <success xmlns="urn:ietf:params:xml:ns:xmpp-sasl"/>
06:46:37 PM SENT (0): <stream:stream xmlns='jabber:client' to='FCM XMPP Client Connection Server' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' id='7CC66277CAAAFA41' xml:lang='en'>
06:46:37 PM RECV (0): <stream:stream from="FCM XMPP Client Connection Server" id="B65CB27C75F39141" version="1.0" xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client">
06:46:37 PM RECV (0): <stream:features><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/></stream:features>
мар 02, 2017 6:46:37 PM com.wedevol.xmpp.server.CcsClient$4 processPacket
INFO: Sent: {}
06:46:37 PM SENT (0): <iq id='kPhH7-1' type='set'><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'><resource>Smack</resource></bind></iq>
06:46:37 PM RECV (0): <iq id="kPhH7-1" type="result"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><jid>PROJECTKEY@gcm.googleapis.com/Smack4FF897B5</jid></bind></iq>
06:46:37 PM RECV (0):  
мар 02, 2017 6:46:37 PM com.wedevol.xmpp.server.CcsClient$4 processPacket
INFO: Sent: {}
06:46:37 PM SENT (0): <iq id='kPhH7-3' type='set'><session xmlns='urn:ietf:params:xml:ns:xmpp-session'/></iq>
06:46:37 PM RECV (0): <iq type="result" id="kPhH7-3"/>
06:46:37 PM User logged (0): PROJECTKEY@gcm.googleapis.com:5236/Smack4FF897B5
06:46:37 PM XMPPConnection authenticated (0)
мар 02, 2017 6:46:37 PM com.wedevol.xmpp.server.CcsClient$2 authenticated
INFO: User authenticated
мар 02, 2017 6:46:37 PM com.wedevol.xmpp.server.CcsClient connect
INFO: Logged in: PROJECTKEY@gcm.googleapis.com
06:46:37 PM SENT (0): <message id='kPhH7-5'><gcm xmlns="google:mobile:data">{"data":{"message":"This is the simple sample message"},"message_id":"m-4967f3b9-c823-4837-ab80-e78ae3292ae1","to":"REGTOKEN"}</gcm></message>
мар 02, 2017 6:46:37 PM com.wedevol.xmpp.server.CcsClient$4 processPacket
INFO: Sent: {}
06:46:37 PM RECV (0): <message><data:gcm xmlns:data="google:mobile:data">{"message_type":"ack","from":"REGTOKEN","message_id":"m-4967f3b9-c823-4837-ab80-e78ae3292ae1"}</data:gcm></message>
мар 02, 2017 6:46:37 PM com.wedevol.xmpp.server.CcsClient processPacket
INFO: Received: <message><gcm xmlns="google:mobile:data">{"message_type":"ack","from":"REGTOKEN","message_id":"m-4967f3b9-c823-4837-ab80-e78ae3292ae1"}</gcm></message>
06:47:03 PM RECV (0):  
06:52:03 PM RECV (0):  
`

**Comment by carlosCharz** [comment]
Hi,
I cannot understand what the problem was. Can you be more specified? What you were doing and what you expected? 
BTW: check the new version of my code: https://github.com/carlosCharz/fcmxmppserverv2

**Comment by fruitJazzy** [comment]
Using https://github.com/carlosCharz/fcmxmppserverv2
What i do:
Added to param project key, server key, reg token
Run app
In logs it is written that the message was sent and received
Expected: the notice comes on the phone

**Comment by carlosCharz** [comment]
It could be a problem with the registration token so. Try to send a test message from the console just to make sure that the token is valid and it is reachable.

**Comment by fruitJazzy** [comment]
The token is correct. Can send a message via http to this token

**Comment by carlosCharz** [comment]
Token OK
Credentials OK
Device OK
Logs OK (It seems to be ok)

To be honest I dont know what it could be. Sorry :(
